// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithReliabilityKit.Modules.Notifications.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithReliabilityKit.Modules.Notifications.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationsContext))]
    [Migration("20260630070459_InitialNotifications")]
    partial class InitialNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModulithReliabilityKit.BuildingBlocks.Application.Inbox.InboxDeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("MovedToDeadLetterOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moved_to_dead_letter_on_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<Guid>("OriginalMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_message_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution_status");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("text")
                        .HasColumnName("resolved_by");

                    b.Property<DateTime?>("ResolvedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("inbox_dead_letters", "notifications");
                });

            modelBuilder.Entity("ModulithReliabilityKit.BuildingBlocks.Application.Inbox.InboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRetryOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_on_utc");

                    b.Property<Guid>("LogicalId")
                        .HasColumnType("uuid")
                        .HasColumnName("logical_id");

                    b.Property<DateTime?>("NextRetryOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_on_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("LogicalId", "OccurredOnUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_notifications_inbox_logical_occurred");

                    b.HasIndex("Status", "NextRetryOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_notifications_inbox_pending");

                    b.ToTable("inbox_messages", "notifications");
                });

            modelBuilder.Entity("ModulithReliabilityKit.Modules.Notifications.Infrastructure.ProductAnnouncements.ProductAnnouncement", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("AnnouncedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("announced_on_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("ProductId");

                    b.ToTable("product_announcements", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
